### ISSUE TITLE
Выбранный цвет на странице товара

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#10]
У выбранного цвета на странице товара должна быть обводка, сейчас она всегда у белого цвета. Белый при этом должен быть с серой обводкой, если не выбран. Думаю через js делать это - проверять стили и добавлять обводку, чтобы не мучить сборщика классами

<details><summary>Details</summary>

![image](https://github.com/aaccent/retrova_layout/assets/36298346/7f7e5551-e714-486c-992e-19721ce4dd3e)
</details>

**Comment by EduardoAlparov** [comment]
исправил
