### ISSUE TITLE
Верстка статьи

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#19]
- Нужно переверстать контентную часть статьи и типовой страницы согласно [этим правилам](https://knowledge.aaccent.ru/layout.html#content-text)
- Проверить отступы между блоками текста и h* элементами

**Comment by EduardoAlparov** [comment]
не понял, где по этой ссылке инструкция для статьи, 
посмотри сейчас

**Comment by foxhable** [comment]
Да, у нас ссылки поменялись. Актуальная [ссылка](https://knowledge.aaccent.ru/layout-process.html#content-text). Там те же правила, что и в этой проблеме https://github.com/aaccent/loginov_layout/issues/41

**Comment by EduardoAlparov** [comment]
исправил
