### ISSUE TITLE
Видео в статье

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#20]
Изменить видео в статьях на ютубовские

**Comment by EduardoAlparov** [comment]
изменил

**Comment by foxhable** [comment]
Вроде iframe ютуба не вставлен, после запуска белый область

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/retrova_layout/assets/36298346/76ba008b-b02a-4e1f-840b-ade61570c5b5)
</details>

**Comment by EduardoAlparov** [comment]
api сам вставляет айфрем, у меня все нормально работает
