### ISSUE TITLE
Оформление сертификатов

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#21]
- Переделать модалку оформления сертификата. Нужно сделать её как заявку с именем и номером, инструкция и о сертификате - это убери. 
- Поменяй заголовок "Сертификат на 1000₽" на "Оформление сертификата"

**Comment by EduardoAlparov** [comment]
переделал

**Comment by foxhable** [comment]
Поменяй ещё заголовок "Куда отправить сертификат" на "Данные для заявки"

**Comment by EduardoAlparov** [comment]
поменял
