### ISSUE TITLE
Карта в контактах

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#24]
- Подправить кликабельную зону точки
- Исправить соответствуя макету

**Comment by EduardoAlparov** [comment]
исправил

**Comment by foxhable** [comment]
1. Заголовок "Контакты" в макете по центру
2. Плавающий элемент `.contacts-page__map-popup.map-popup` с информацией в макете находится слева
3. Кликабельная зона должна включать в себя и белую хренотень, не только буква "R"

<details><summary>Видео кликабельной зоны</summary>

https://github.com/aaccent/retrova_layout/assets/36298346/b2f6d400-1c49-45d1-b147-d786262a9c23
</details>

**Comment by EduardoAlparov** [comment]
исправил
