### ISSUE TITLE
Адрес доставки на оформлении

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#26]
Кнопки очистки полей пропадают на полях

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/retrova_layout/assets/36298346/74388213-4d38-4d64-9747-2cdb44704c01)
</details>

**Comment by EduardoAlparov** [comment]
они всегда пропадают без фокуса

**Comment by foxhable** [comment]
Точно, правки не мои, поэтому иногда бред проскакивает
