### ISSUE TITLE
Выбор пункта выдачи

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#27]
- Кнопки масштаба не работают
- Нужно добавить метки на карту. Координаты меток должны парсится из списка пунктов выдачи
- При вводе поиска появляются обе иконки на поле - крестика и поиска

**Comment by EduardoAlparov** [comment]
Кнопки масштаба не работают -у меня работают.
 Координаты меток должны парсится из списка пунктов выдачи - какие координаты?

**Comment by foxhable** [comment]
В разметке есть список пунктов
```html
<li class="modal-del-point__results-item" data-place=""></li>
<li class="modal-del-point__results-item" data-place=""></li>
<li class="modal-del-point__results-item" data-place=""></li>
<li class="modal-del-point__results-item" data-place=""></li>
```

Добавь к элементам тестовые координаты точек
```html
<li class="modal-del-point__results-item" data-place="" data-coords="45.2343,59.21321"></li>
<li class="modal-del-point__results-item" data-place="" data-coords="45.2343,59.21321"></li>
<li class="modal-del-point__results-item" data-place="" data-coords="45.2343,59.21321"></li>
<li class="modal-del-point__results-item" data-place="" data-coords="45.2343,59.21321"></li>
```

И выводи их на карту. Точки на карте при клике должны действовать так-же, как и при клике на "выбрать пункт"

**Comment by EduardoAlparov** [comment]
исправил
