### ISSUE TITLE
Способ оплаты на оформлении

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#29]
Добавить описание к способу

<details><summary>Details</summary>

![image](https://github.com/aaccent/retrova_layout/assets/36298346/88ab1ad9-1587-41c4-a8bd-b02ceec64ef4)
</details>

**Comment by EduardoAlparov** [comment]
там есть описание

**Comment by foxhable** [comment]
Она есть, но только в активном состоянии. Пользователю для принятия решения нужно это описание до выбора

**Comment by EduardoAlparov** [comment]
исправил
