### ISSUE TITLE
Таблица размеров

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#3]
Если здесь перейти на таблицу размеров, затем закрыть ее, закрывается и сам фильтр. Сделать чтобы закрывалась только модалка с таблицей, а фильтр оставался открытым
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/retrova_layout/assets/36298346/fa63ed4b-ddfa-4959-86f7-3446ae27a453)
</details>

**Comment by EduardoAlparov** [comment]
исправлено
