### ISSUE TITLE
Поля регистрации

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#33]
В поле ввода мыла текст белый

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/retrova_layout/assets/36298346/f6df6d1b-650f-4442-8e77-185f682cf99c)
</details>

**Comment by EduardoAlparov** [comment]
у меня нормально, в стилях нигде нет белого инпута

**Comment by foxhable** [comment]
Забей, гении на команде разработки Эджа снова херню какую-то сделали. Он при вводе наследует цвет у родителя, а он белый. Потом сам подправлю
![image](https://github.com/aaccent/retrova_layout/assets/36298346/9a76330b-79a8-4a1a-b4f2-3a95c44387d3)
