### ISSUE TITLE
Кнопка "Назад" в попапе кода

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#34]
Кнопка не отправляет на предыдущий попап с вводом мыла, а перезагружает страницу, т.к. она ссылка

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/retrova_layout/assets/36298346/f121f147-3e3f-404a-8cb8-ee90f0d0353f)
</details>

**Comment by EduardoAlparov** [comment]
исправил
