### ISSUE TITLE
Счётчик фильтров

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#4]
Если выбрать несколько пунктов в фильтре, а потом нажать показать, то слева, на кнопке открытия фильтров отображается количество выбранных пунктов. Если убрать некоторые пункты и нажать показать, то это количество не изменяется

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/retrova_layout/assets/36298346/1cecd7a9-618d-4ecd-9e35-b5dbf23e92db)
</details>

**Comment by EduardoAlparov** [comment]
исправлено
