### ISSUE TITLE
Подкатегории на каталоге 1 уровня

### ISSUE THREAD

**Issue by foxhable** [aaccent/retrova_layout#5]
Кнопка "Ещё" скрывается сама, если количество элементов меньше, чем необходимо для скрытия? Если не скрывается, то нужно сделать

<details><summary>Details</summary>

![image](https://github.com/aaccent/retrova_layout/assets/36298346/ec23ddf9-ef85-4506-ae72-1a07497e66d4)
</details>

**Comment by EduardoAlparov** [comment]
сделано
